version: 2

updates:
  - package-ecosystem: "gomod"
    directories:
      - "/tools/apklabel"
      - "/tools/appaudit"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
